version: '3'
services:
  nginx-unit:
    build: ./unit
    working_dir: /var/www/
    ports:
      - "80:80"
    volumes:
      - ./unit/config.json:/docker-entrypoint.d/config.json
      - ./../.:/var/www
